heat_template_version: 2021-04-16

description: A template to deploy all infrastructure needed for `airun`.

parameters:
  instance_exists:
    type: boolean
    label: Instance exists
    description: >
      Set to true to ensure the instance exists.
      Set to false to ensure the instance gets destroyed if it exists.
    default: false
  instance_name:
    type: string
    label: Instance name
    constraints:
    - allowed_pattern: "[a-zA-Z0-9-]+"
    default: "airun-instance"
  instance_image:
    type: string
    label: Instance image
    description: OpenStack VM image to use to launch the instance
    constraints:
    - allowed_pattern: "[a-zA-Z0-9- ]+"
    default: "airun-image"
  instance_flavor:
    type: string
    label: Instance flavor
    constraints:
    - allowed_pattern: "[a-zA-Z0-9-]+"
    default: "nvl4-a4-ram8-disk80-perf1"
  key_name:
    type: string
    label: Key name
    description: Name of the keypair to use for the instance
    default: "airun_key"

conditions:
  instance_exists:
    get_param: instance_exists

resources:
  airun_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: airun-security-group
      description: Security group for the airun instance - allows SSH ingress.
      rules:
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22
          remote_ip_prefix: 0.0.0.0/0

  airun_volume:
    type: OS::Cinder::Volume
    properties:
      name: airun-volume
      size: 128

  airun_instance:
    type: OS::Nova::Server
    condition: instance_exists
    properties:
      name:
        get_param: instance_name
      key_name:
        get_param: key_name
      image:
        get_param: instance_image
      flavor:
        get_param: instance_flavor
      networks:
        - network: "ext-net1"
      security_groups:
        - get_resource: airun_security_group

  airun_instance_attachment:
    type: OS::Cinder::VolumeAttachment
    condition: instance_exists
    properties:
      instance_uuid:
        get_resource: airun_instance
      volume_id:
        get_resource: airun_volume
      mountpoint: /dev/vdb

outputs:
  airun_instance_ip:
    condition: instance_exists
    description: IPv4 address of the airun instance
    value:
      get_attr:
        - airun_instance
        - first_address

